name: publish

on: [push]

jobs:
  publish-jenkins-exporter-image:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/arnaudlemaignen/jenkins-exporter:latest
        docker push ghcr.io/arnaudlemaignen/jenkins-exporter:latest
